# fly.toml app configuration file generated for 5-second-rule-go on 2023-06-12T07:43:54+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "5-second-rule-go"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
